name: screenshot2
on:
  schedule:
  - cron: '0 10 * * *'

jobs:
  capa_de_jornal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      - name: Install packages
        run: |   
          R -e 'install.packages("webshot2")'
        
      - name: Take screenshots
        run: Rscript screenshot_script.R
